include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: true
    always_use_package_imports: true
    prefer_single_quotes: true

analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.mocks.dart'
    - '**.mocks.reflectable.dart'
    - '**.reflectable.dart'
    - '**.g.dart'
    - '**/generated_plugin_registrant.dart'
    - '**/assets.gen.dart'
    - '**/fonts.gen.dart'
    - 'lib/injectable.config.dart'
    - 'lib/di/injectable.config.dart'
#    - 'lib/main.dart'
#    - 'lib/main_dev.dart'
#    - 'lib/main_staging.dart'
#    - 'lib/main_prod.dart'

  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  rules:
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else