name: m_banking_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  injectable: ^2.3.2
  go_router: ^14.1.4
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.4.2
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/translations/


flutter_gen:
  output: lib/generated/
  line_length: 120